### ISSUE TITLE
Cannot run program adb

### ISSUE THREAD

**Issue by ke-shen** [Genymobile/gnirehtet#111]
Cannot run program "adb": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.genymobile.gnirehtet.Main.mustInstallClient(Main.java:345)
	at com.genymobile.gnirehtet.Main.cmdStart(Main.java:256)
	at com.genymobile.gnirehtet.Main.lambda$cmdRun$0(Main.java:223)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 4 more
2018-05-23 21:00:17.526 I Relay: Relay server started

Here is the error. I even pasted the contents of the adb directory into the gnirehtet directory. Any suggestions?

**Comment by rom1v** [comment]
On Linux, you need `adb` to be accessible from your `PATH`:

```bash
export PATH="/path/to/adb/directory:$PATH"
./gnirehtet …
```

Instead, you could also check whether `adb` is available from you distribution, so that you can install its package. For example, on _Debian_:

    adb install android-tools-adb

**Comment by ke-shen** [comment]
Thank you for the fast reply. what is the syntax that I should have for MAC?

**Comment by rom1v** [comment]
> Thank you for the fast reply. what is the syntax that I should have for MAC?

The very same as on Linux.
