### ISSUE TITLE
Connection Request confirmation does not appear

### ISSUE THREAD

**Issue by realn3wb13** [Genymobile/gnirehtet#135]
![image](https://user-images.githubusercontent.com/33515872/43495587-77f5309a-956b-11e8-8503-bfc089585c60.png)

But the connection request confirmation did not appear. I tried to re-install, reboot both phone and PC. I also tried both java and rust but the same result.

![image](https://user-images.githubusercontent.com/33515872/43495687-fe0e0f26-956b-11e8-933b-6d6878cc900f.png)

**Comment by rom1v** [comment]
I already had this problem, on some devices (but make it work after uninstall/reinstall gnirehtet). I don't know the cause.

Are there relevant logs in `adb logcat`?

**Comment by realn3wb13** [comment]
Sorry I don't know who to view logcat

**Comment by rom1v** [comment]
> Sorry I don't know who to view logcat

Just execute `adb logcat` from a terminal (the directory containing `adb` must be in `PATH`).

On one of my devices, if the dialog opens when the phone is locked, when I unlock the app showing the dialog crashes with this stack trace:

```
E VpnConfirm: onResume
E VpnConfirm: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
E VpnConfirm: 	at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:317)
E VpnConfirm: 	at com.android.internal.app.AlertController.installContent(AlertController.java:231)
E VpnConfirm: 	at com.android.internal.app.AlertActivity.setupAlert(AlertActivity.java:90)
E VpnConfirm: 	at com.android.vpndialogs.ConfirmDialog.onResume(ConfirmDialog.java:72)
E VpnConfirm: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
E VpnConfirm: 	at android.app.Activity.performResume(Activity.java:6327)
E VpnConfirm: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
E VpnConfirm: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
E VpnConfirm: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1388)
E VpnConfirm: 	at android.os.Handler.dispatchMessage(Handler.java:102)
E VpnConfirm: 	at android.os.Looper.loop(Looper.java:148)
E VpnConfirm: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
E VpnConfirm: 	at java.lang.reflect.Method.invoke(Native Method)
E VpnConfirm: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E VpnConfirm: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by realn3wb13** [comment]
I hope this is the right one.

![image](https://user-images.githubusercontent.com/33515872/43695751-0d12b3fa-996d-11e8-961f-7a51457ef2b7.png)

**Comment by rom1v** [comment]
@realn3wb13 It seems there is a crash, indeed, but the backtrace is above your screenshot :)

Save the result in a file and paste the relevant parts:

    adb logcat -d > file.txt

**Comment by realn3wb13** [comment]
Thanks. I hope this has all the info. 

[file.txt](https://github.com/Genymobile/gnirehtet/files/2262144/file.txt)

**Comment by rom1v** [comment]
Thanks.

So, no, it's not related to any crash. It's only:

    W BroadcastQueue: Reject to launch app com.genymobile.gnirehtet/10138 for broadcast: App Op 63

Don't know how to avoid it. It seems related to an app in "forced stop" state, but since gnirehtet has no activity, an user may never start it manually to change its state.

**Comment by realn3wb13** [comment]
@rom1v 
Thanks bro I found a solution in [https://stackoverflow.com/questions/34842659/cannot-autostart-app-on-boot-got-broadcastqueue-reject-to-launch-app](stackoverflow) turns out it's an embedded app in my phone.
