### ISSUE TITLE
adb: failed to install gnirehtet.apk

### ISSUE THREAD

**Issue by kaisonchan** [Genymobile/gnirehtet#139]
It works perfectly with my office computer until I try to make it on my own PC (and fail). 
After that, I can't use gnirehtet with my office computer, it shows the message as below when I run gnirehtet-run.cmd.
What should I do to fix this problem?

2018-08-30 09:28:59.988 I Gnirehtet: Checking gnirehtet client...
2018-08-30 09:29:00.093 I Gnirehtet: Installing gnirehtet client...
adb: failed to install gnirehtet.apk: Failure [INSTALL_FAILED_VERSION_DOWNGRADE]

Exception in thread "main" com.genymobile.gnirehtet.relay.CommandExecutionExcept
ion: Command [adb, install, -r, gnirehtet.apk] returned with value 1
        at com.genymobile.gnirehtet.Main.execSync(Main.java:218)
        at com.genymobile.gnirehtet.Main.execAdb(Main.java:192)
        at com.genymobile.gnirehtet.Main.access$100(Main.java:32)
        at com.genymobile.gnirehtet.Main$Command$1.execute(Main.java:53)
        at com.genymobile.gnirehtet.Main$Command$4.execute(Main.java:96)
        at com.genymobile.gnirehtet.Main.main(Main.java:329)
Press any key to continue . . .

**Comment by kaisonchan** [comment]
Problem solved, I'm using the old version gnirehtet on my office computer, what I have to do is just simply replace the new version files to the old folder.
