### ISSUE TITLE
relay dies with  AssertionError

### ISSUE THREAD

**Issue by tseglevskiy** [Genymobile/gnirehtet#154]
One real device, connected by USB. In some time relay dies. What's wrong?

```
➜  gnirehtet-java ./gnirehtet relay                                                                     
2018-11-09 17:41:13.395 I Gnirehtet: Starting relay server...
2018-11-09 17:41:13.456 I Relay: Relay server started
2018-11-09 17:41:17.458 I TunnelServer: Client #0 connected
2018-11-09 17:41:17.544 I TCPConnection: TCP 10.0.0.2:49290 -> 10.118.203.233:80 Open
2018-11-09 17:41:17.546 I TCPConnection: TCP 10.0.0.2:49291 -> 10.118.203.233:80 Open
2018-11-09 17:41:17.546 I TCPConnection: TCP 10.0.0.2:49292 -> 10.118.203.233:80 Open
2018-11-09 17:41:17.618 I TCPConnection: TCP 10.0.0.2:49290 -> 10.118.203.233:80 Close
2018-11-09 17:41:17.624 I TCPConnection: TCP 10.0.0.2:49291 -> 10.118.203.233:80 Close
2018-11-09 17:41:17.625 I TCPConnection: TCP 10.0.0.2:49292 -> 10.118.203.233:80 Close
2018-11-09 17:41:32.995 I TCPConnection: TCP 10.0.0.2:49293 -> 10.118.203.233:80 Open
2018-11-09 17:41:32.996 I TCPConnection: TCP 10.0.0.2:49294 -> 10.118.203.233:80 Open
2018-11-09 17:41:33.372 I TCPConnection: TCP 10.0.0.2:49295 -> 10.118.203.233:80 Open
2018-11-09 17:41:33.376 I TCPConnection: TCP 10.0.0.2:49296 -> 10.118.203.233:80 Open
2018-11-09 17:41:43.358 I TCPConnection: TCP 10.0.0.2:49297 -> 10.118.203.233:80 Open
2018-11-09 17:41:43.400 I TCPConnection: TCP 10.0.0.2:49298 -> 10.118.203.233:80 Open
2018-11-09 17:42:15.467 I TCPConnection: TCP 10.0.0.2:49298 -> 10.118.203.233:80 Close
2018-11-09 17:42:15.468 I TCPConnection: TCP 10.0.0.2:49293 -> 10.118.203.233:80 Close
2018-11-09 17:42:15.469 I TCPConnection: TCP 10.0.0.2:49296 -> 10.118.203.233:80 Close
2018-11-09 17:42:15.469 I TCPConnection: TCP 10.0.0.2:49297 -> 10.118.203.233:80 Close
2018-11-09 17:42:15.469 I TCPConnection: TCP 10.0.0.2:49294 -> 10.118.203.233:80 Close
2018-11-09 17:42:15.470 I TCPConnection: TCP 10.0.0.2:49295 -> 10.118.203.233:80 Close
2018-11-09 17:42:15.480 I UDPConnection: UDP 10.0.0.2:5218 -> 8.8.8.8:53 Open
Exception in thread "main" java.lang.AssertionError: selector.select() returned without any event, an invalid SelectionKey was probably been registered
	at com.genymobile.gnirehtet.relay.Relay.run(Relay.java:60)
	at com.genymobile.gnirehtet.Main.cmdRelay(Main.java:296)
	at com.genymobile.gnirehtet.Main.access$1100(Main.java:32)
	at com.genymobile.gnirehtet.Main$Command$11.execute(Main.java:187)
	at com.genymobile.gnirehtet.Main.main(Main.java:427)
➜  gnirehtet-java
```

**Comment by rom1v** [comment]
Thank you for the report. On which platform? Does it also happen with the rust version?

Possibly related to https://github.com/Genymobile/gnirehtet/issues/136.

**Comment by tseglevskiy** [comment]
It's gnirehtet-java-v2.3.zip, MacOS and Samsung tablet.

No, I didn't try the rust version. Can it help?

**Comment by rom1v** [comment]
Note for find the cause: this might be correlated with unreachable DNS: https://github.com/Genymobile/gnirehtet/issues/155.

**Comment by sargissargsyan** [comment]
I have the same issue on mac OS. any update on this?
