### ISSUE TITLE
Issue while launching for the first time...

### ISSUE THREAD

**Issue by gugagom** [Genymobile/gnirehtet#164]
I gave a look into other issues posted but I couldn't find any look-a-like to my issue. Maybe I'm even doing something dumb but I couldn't workout what am I doing.

Launching the program for the first time it seems to be running, but no vpn or internet is brought up.
I looked into the tutorial in the homepage again and did everything from zero. No result. I'm posting the cut-log of the window so you can workout something.

```
D:\Downloads\gnirehtet-java>gnirehtet autorun
2019-01-08 14:01:10.959 I Gnirehtet: Starting relay server...
2019-01-08 14:01:10.959 I Gnirehtet: Checking gnirehtet client...
2019-01-08 14:01:11.152 I Gnirehtet: Starting client...
Android Debug Bridge version 1.0.31

[ADB Help Page]

2019-01-08 14:01:11.920 E Gnirehtet: Cannot start client
com.genymobile.gnirehtet.relay.CommandExecutionException: Command [adb, -s, 0043408867, reverse, localabstract:gnirehtet, tcp:31416] returned with value 1
        at com.genymobile.gnirehtet.Main.execSync(Main.java:336)
        at com.genymobile.gnirehtet.Main.execAdb(Main.java:310)
        at com.genymobile.gnirehtet.Main.cmdTunnel(Main.java:291)
        at com.genymobile.gnirehtet.Main.cmdStart(Main.java:257)
        at com.genymobile.gnirehtet.Main.lambda$asyncStart$3(Main.java:302)
        at java.lang.Thread.run(Unknown Source)
```
Edit1: Fixing code inserting.
Edit2: Clarification about editing.

**Comment by rom1v** [comment]
> Android Debug Bridge version 1.0.31
You need a more recent vesion of [adb](https://github.com/Genymobile/gnirehtet#adb). Yours does not support `adb reverse`.

**Comment by gugagom** [comment]
> > Android Debug Bridge version 1.0.31
> 
> You need a more recent version of [adb](https://github.com/Genymobile/gnirehtet#adb). 1.0.31 does not support `adb reverse`.

Holy ****!
Thanks, I updated the adb I had and it passed with flying colors.

Regards,
gugagom
