### ISSUE TITLE
gnirehtet-java-v2.4 + Java Version 8 Update 231 on Win7x64 = Error

### ISSUE THREAD

**Issue by svladimirs** [Genymobile/gnirehtet#244]
gnirehtet-java-v2.3 + Java Version 8 Update 231 (build 1.8.0_231-b11) = working
gnirehtet-java-v2.4 + Java Version 8 Update 231 (build 1.8.0_231-b11) = error
There is no update for Java (newest).

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/genymobile/gnirehtet/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by rom1v** [comment]
Oh, you need java 11, I built the jar with OpenJDK 11.

**Comment by svladimirs** [comment]
Thank you for continue working with gnirehtet and answer!
Did I understand correctly, that there is no OpenJDK 11 for Win x86? Therefore, we should forget gnirehtet-java-v2.4 for Win x86? This was one way to use gnirehtet on win x86 :(

**Comment by rom1v** [comment]
I just added a zip containing a version compatible with java 8: https://github.com/Genymobile/gnirehtet/releases/tag/v2.4

**Comment by svladimirs** [comment]
Thank you very much! It works. But two notes:
1) I offer to do equally INFO, ERROR in Rust and I, E in Java
2) Remove lines which starts 'at' in Java.

Rust:
2019-11-21 09:18:50.244 INFO Main: Starting relay server on port 31416...
2019-11-21 09:18:50.245 INFO Relay: Relay server started
2019-11-21 09:18:51.240 ERROR AdbMonitor: Failed to monitor adb devices: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (os error 10061)
2019-11-21 09:18:51.240 INFO AdbMonitor: Restarting adb daemon
* daemon not running; starting now at tcp:5037
* daemon started successfully
2019-11-21 09:18:56.280 INFO Main: Checking gnirehtet client...
2019-11-21 09:18:56.356 INFO Main: Starting client...
2019-11-21 09:18:57.287 INFO TunnelServer: Client #0 connected

Java:
2019-11-21 09:21:51.639 I Gnirehtet: Starting relay server on port 31416...
2019-11-21 09:21:51.689 I Relay: Relay server started
2019-11-21 09:21:52.636 E AdbMonitor: Failed to monitor adb devices
java.net.ConnectException: Connection refused: connect
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
        at com.genymobile.gnirehtet.AdbMonitor.trackDevices(AdbMonitor.java:75)
        at com.genymobile.gnirehtet.AdbMonitor.monitor(AdbMonitor.java:64)
        at com.genymobile.gnirehtet.Main.cmdAutostart(Main.java:280)
        at com.genymobile.gnirehtet.Main.lambda$cmdAutorun$1(Main.java:243)
        at java.lang.Thread.run(Unknown Source)
2019-11-21 09:21:52.637 I AdbMonitor: Restarting adb deamon
* daemon not running; starting now at tcp:5037
* daemon started successfully
2019-11-21 09:21:57.682 I Gnirehtet: Checking gnirehtet client...
2019-11-21 09:21:57.770 I Gnirehtet: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetAc
tivity (has extras) }
2019-11-21 09:21:59.035 I TunnelServer: Client #0 connected

**Comment by rom1v** [comment]
After `Client #0 connected`, nothing happens?

**Comment by svladimirs** [comment]
After 'Client #0 connected' run other information. Both versions (Rust and Java) works correctly. I only offered to change displaying info. This issue we can close. Thank you.
