### ISSUE TITLE
gnirehtet does not work (windows 7 x86)

### ISSUE THREAD

**Issue by NightAngel567** [Genymobile/gnirehtet#248]
gnirehtet does not work (windows 7 x86)

2019-11-29 00:08:57.749 I Gnirehtet: Checking gnirehtet client...
2019-11-29 00:08:57.749 I Gnirehtet: Starting relay server...
2019-11-29 00:08:57.792 E Gnirehtet: Cannot start client
com.genymobile.gnirehtet.relay.CommandExecutionException: Command [adb, shell, d
umpsys, package, com.genymobile.gnirehtet] returned with value 1
        at com.genymobile.gnirehtet.Main.mustInstallClient(Main.java:347)
        at com.genymobile.gnirehtet.Main.cmdStart(Main.java:250)
        at com.genymobile.gnirehtet.Main.lambda$asyncStart$3(Main.java:302)
        at java.lang.Thread.run(Unknown Source)
2019-11-29 00:08:57.891 I Relay: Relay server started

established: Java 8 Update 221 and 231 and Java SE Development Kit 8 Update 221
in this thread they write that it works on x86 
https://github.com/Genymobile/gnirehtet/issues/184

**Comment by NightAngel567** [comment]
close the topic earned

**Comment by rom1v** [comment]
Do you have `adb`?

> close the topic earned

So problem fixed?
