### ISSUE TITLE
no vpn popup

### ISSUE THREAD

**Issue by LeiJunOK** [Genymobile/gnirehtet#251]
2019-12-07 20:09:48.458 INFO Main: Checking gnirehtet client...
2019-12-07 20:09:48.458 INFO Main: Starting relay server on port 31416...
2019-12-07 20:10:04.991 INFO Relay: Relay server started
2019-12-07 20:10:10.231 INFO Main: Installing gnirehtet client...
Performing Streamed Install
Success
2019-12-07 20:10:17.037 INFO Main: Starting client...

Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=6501, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=6501, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1709)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:469)
        at com.android.server.am.ActivityStarter.startActivityLocked(ActivityStarter.java:285)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:942)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:752)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4748)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:417)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:141)
        at android.os.ShellCommand.exec(ShellCommand.java:96)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15563)
        at android.os.Binder.shellCommand(Binder.java:597)
        at android.os.Binder.onTransact(Binder.java:495)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4328)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3031)
        at android.os.Binder.execTransact(Binder.java:704)
2019-12-07 20:10:17.184 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
See #5
