### ISSUE TITLE
Hi,  I ran my appium program in eclipse for first time. When ran the program getting the error like "Unable to create the remote session".

### ISSUE THREAD

**Issue by saiimmadi** [Genymobile/gnirehtet#264]

**Comment by saiimmadi** [comment]
Unable to create a new remote session. Please check the server log for more details. Original error: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command ''C:\\Users\\Sai Narasimha\\Downloads\\android-sdk\\platform-tools\\adb.exe' -P 5037 -s 61d838ff shell settings delete global hidden_api_policy_pre_p_apps' exited with code 255'; Stderr: 'Security exception: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS
 at com.android.providers.settings.SettingsProvider.enforceWritePermission(SettingsProvider.java:1815)
 at com.android.providers.settings.SettingsProvider.mutateGlobalSetting(SettingsProvider.java:1023)
 at com.android.providers.settings.SettingsProvider.deleteGlobalSetting(SettingsProvider.java:1006)
 at com.android.providers.settings.SettingsProvider.delete(SettingsProvider.java:592)
 at android.content.ContentProvider$Transport.delete(ContentProvider.java:343)
 at com.android.providers.settings.SettingsService$MyShellCommand.deleteForUser(SettingsService.java:406)
 at com.android.providers.settings.SettingsService$MyShellCommand.onCommand(SettingsService.java:289)
 at android.os.ShellCommand.exec(ShellCommand.java:103)
 at com.android.providers.settings.SettingsService.onShellCommand(SettingsService.java:51)
 at android.os.Binder.shellCommand(Binder.java:634)
 at android.os.Binder.onTransact(Binder.java:532)
 at android.os.Binder.execTransact(Binder.java:735)'; Code: '255'
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DESKTOP-O0R4C7N', ip: '192.168.1.7', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_241'
Driver info: driver.version: AppiumDriver

**Comment by rom1v** [comment]
>     java.lang.SecurityException: Permission denial: writing to settings requires:android.permission.WRITE_SECURE_SETTINGS

#5

**Comment by saiimmadi** [comment]
Hi rom1v,

I have seen below is is the solution to resolve this issue.

The issue seems to be resolved by heading over to Developer Options on MIUI, and enabling the following:
USB debugging -Debug mode when USB is connected
Install via USB -Allow installing apps via USB
USB debugging (Security Settings)- Allow granting permissions and simulating input via USB debugging

The first was already enabled, and I installed the apk file manually so I didn't need the second option.

I'm guessing the issue can be pinned down to the last option, which allows granting the necessary permissions. @CoderBuck please confirm.

Thank you @rom1v for this amazing app. This is a worthy free replacement for ReverseTethering NoRoot.

But i have some doubts here. Please clarify those.
1)USB Debugging-- i did in my mobile device with out any issue.
2) I installed the apk file manually so I didn't need the second option.(what is apk file? It means apk app in the mobile device, please correct me if i'm wrong.
3)USB debugging (Security Settings)-- How to do this one. I dont have idea. Please explain clearly

Thanks in Advance!!
