### ISSUE TITLE
Command adb returned with value -1

### ISSUE THREAD

**Issue by Petersaber** [Genymobile/gnirehtet#292]
When trying to execute gnirehtet, I get the following result:

C:\Users\Petersaber\Desktop\gnirehtet>gnirehtet run
2020-04-17 10:44:44.184 INFO Main: Checking gnirehtet client...
2020-04-17 10:44:44.184 INFO Main: Starting relay server on port 31416...
2020-04-17 10:44:44.190 INFO Relay: Relay server started
2020-04-17 10:44:44.337 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START
cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent {
act=com.genymobile.gnirehtet.START flg=0x10000000
cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=10353,
uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent {
act=com.genymobile.gnirehtet.START flg=0x10000000
cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=10353,
uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
         at
com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1857)
         at
com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:762)
         at
com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:562)
         at
com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1279)
         at
com.android.server.am.ActivityStarter.execute(ActivityStarter.java:500)
         at
com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5296)
         at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5270)
         at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)
         at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
         at android.os.ShellCommand.exec(ShellCommand.java:103)
         at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16612)
         at android.os.Binder.shellCommand(Binder.java:629)
         at android.os.Binder.onTransact(Binder.java:527)
         at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3499)
         at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3369)
         at android.os.Binder.execTransact(Binder.java:726)
2020-04-17 10:44:44.659 ERROR Main: Cannot start client: Command adb
["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n",
"com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value -1

**Comment by rom1v** [comment]
#5
