### ISSUE TITLE
i cant connect my phone

### ISSUE THREAD

**Issue by Galcool** [Genymobile/gnirehtet#296]
i need help again, when i run gnirehtet i get this:
0-04-21 23:03:24.355 INFO Main: Starting relay server on port 31416...
2020-04-21 23:03:24.357 INFO Main: Checking gnirehtet client...
2020-04-21 23:03:24.360 INFO Relay: Relay server started
2020-04-21 23:03:24.471 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=561, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=561, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1864)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:751)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:552)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1214)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:494)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5353)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5327)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16685)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3498)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3408)
        at android.os.Binder.execTransact(Binder.java:735)
2020-04-21 23:03:24.635 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255
i get no VPN pop-up
can someone help me?

**Comment by rom1v** [comment]
#5
