### ISSUE TITLE
Returned with value of 255

### ISSUE THREAD

**Issue by Bitik24** [Genymobile/gnirehtet#302]
Hiii. can anyone please help me with this error. This is what I always get when I try to run gnirehtet.
![dddd](https://user-images.githubusercontent.com/65590512/82297829-caf78100-99e5-11ea-9963-99b074ccc564.PNG)

**Comment by Bitik24** [comment]
and this what happens when I type adb devices 
![sads](https://user-images.githubusercontent.com/65590512/82297893-e6fb2280-99e5-11ea-8364-33ca4c25f98a.PNG)

**Comment by rom1v** [comment]
Show the whole error message, by copying the text instead of screenshots.

**Comment by Bitik24** [comment]
2020-05-19 15:57:33.638 INFO Main: Starting relay server on port 31416...
2020-05-19 15:57:33.645 INFO Main: Checking gnirehtet client...
2020-05-19 15:57:33.670 INFO Relay: Relay server started
2020-05-19 15:57:33.798 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnireht
et/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnir
ehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } fro
m null (pid=24576, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymo
bile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActiv
ity } from null (pid=24576, uid=2000) requires android.permission.WRITE_SECURE_S
ETTINGS
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPe
rmission(ActivityStackSupervisor.java:1964)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.j
ava:1106)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.j
ava:667)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivitySt
arter.java:2051)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:60
5)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(Acti
vityManagerService.java:5915)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(Acti
vityManagerService.java:5889)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(Ac
tivityManagerShellCommand.java:479)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityM
anagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityM
anagerService.java:18380)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:35
14)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManag
erService.java:3732)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActiv
ityManagerService.java:919)
        at android.os.Binder.execTransact(Binder.java:731)
2020-05-19 15:57:33.980 ERROR Main: Cannot start client: Command adb ["shell", "
am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnir
ehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
It's #5 then.

**Comment by Bitik24** [comment]
I got it. Apparantly I can just disable permission monitoring in the developer options. Thanks for responding though. ♥

**Comment by MidoFares22** [comment]
> I got it. Apparantly I can just disable permission monitoring in the developer options. Thanks for responding though. ♥

thanks alot finally solved the problem

**Comment by Jazzwind** [comment]
> I got it. Apparantly I can just disable permission monitoring in the developer options. Thanks for responding though. ♥

Could u post a picture of the "disable permission monitoring"? Cause I have the same problem but I can't find it in my developer opinion. Using ColorOS 11.1

**Comment by MidoFares22** [comment]
> > I got it. Apparantly I can just disable permission monitoring in the developer options. Thanks for responding though. ♥
> 
> Could u post a picture of the "disable permission monitoring"? Cause I have the same problem but I can't find it in my developer opinion. Using ColorOS 11.1

it is named disable permission monitoring here is screen shot for it i also have coloros
![Screenshot_2021-11-19-10-08-10-53_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/80355615/142588010-2de07bfa-cafb-4640-b4f2-ae8721bccfc7.jpg)

**Comment by Jazzwind** [comment]
> > > I got it. Apparantly I can just disable permission monitoring in the developer options. Thanks for responding though. ♥
> > 
> > 
> > Could u post a picture of the "disable permission monitoring"? Cause I have the same problem but I can't find it in my developer opinion. Using ColorOS 11.1
> 
> it is named disable permission monitoring here is screen shot for it i also have coloros ![Screenshot_2021-11-19-10-08-10-53_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/80355615/142588010-2de07bfa-cafb-4640-b4f2-ae8721bccfc7.jpg)

！ oh!!! Thanks a lot! I tried to find it in "Debugging" part, but it turns out that it's in "Application" part. I found it, thanks!

为了中文用户，在开发者选项中的“禁止权限监控”，打开就可以了

**Comment by timoTHE-OS** [comment]
this still doesnt work on redmi 11

**Comment by srivetriselvan** [comment]
still dosent work on redmi devices

**Comment by D1narG** [comment]
<img width="454" height="424" alt="Image" src="https://github.com/user-attachments/assets/5cf66f0a-6de7-44fa-91ab-ce51ed8c9dfd" />

Enable those three options on Redmi devices and it will work

**Comment by sedat8879** [comment]
thanks a lot man.

**Comment by sohailnidasohail-svg** [comment]
https://github.com/user-attachments/assets/75cfda3f-00c8-42e1-8da5-b3faca575d58

**Comment by sohailnidasohail-svg** [comment]
> 4_5778459664442200258.mp4
