### ISSUE TITLE
My Android cannot connect to its relay server

### ISSUE THREAD

**Issue by godofrayer** [Genymobile/gnirehtet#31]
Logcat shows

```
W/ADB_SERVICES(  303): create_local_service_socket() name=shell:am startservice -a com.genymobile.gnirehtet.START
W/ADB_SERVICES(  303): service_to_fd() name=shell:am startservice -a com.genymobile.gnirehtet.START
W/ADB_SERVICES(  303): LS(9): bound to 'shell:am startservice -a com.genymobile.gnirehtet.START' via 20
D/ActivityThread( 5805): SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@15bc1463 className=com.genymobile.gnirehtet.GnirehtetControlService packageName=com.genymobile.gnirehtet intent=null}
D/ActivityThread( 5805): SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@15bc1463 className=com.genymobile.gnirehtet.GnirehtetControlService packageName=com.genymobile.gnirehtet intent=null}
D/ActivityThread( 5805): SVC-Calling onStartCommand: com.genymobile.gnirehtet.GnirehtetControlService@36dd0860, flags=0, startId=1
D/GnirehtetControlService( 5805): Received request com.genymobile.gnirehtet.START
I/Vpn     (  895): prepare old:com.genymobile.gnirehtet,new:null
D/ActivityThread( 5805): SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@15bc1463 startId=1 args=Intent { act=com.genymobile.gnirehtet.START }}
D/ActivityThread( 5805): SVC-Calling onStartCommand: com.genymobile.gnirehtet.GnirehtetService@2c9e32eb, flags=0, startId=3
D/GnirehtetService( 5805): Received request com.genymobile.gnirehtet.START_VPN
I/Vpn     (  895): Established by com.genymobile.gnirehtet on tun0
D/ActivityThread( 5805): SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@1572763a startId=3 args=Intent { act=com.genymobile.gnirehtet.START_VPN cmp=com.genymobile.gnirehtet/.GnirehtetService (has extras) }}
D/ActivityThread( 5805): SVC-Destroying service: com.genymobile.gnirehtet.GnirehtetControlService@36dd0860
D/Posix   ( 5805): [Posix_connect Debug]Process com.genymobile.gnirehtet :31416
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.RelayTunnel.connect(RelayTunnel.java:49)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.RelayTunnelProvider.connectTunnel(RelayTunnelProvider.java:77)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.RelayTunnelProvider.getCurrentTunnel(RelayTunnelProvider.java:70)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.PersistentRelayTunnel.receive(PersistentRelayTunnel.java:63)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.Forwarder.forwardTunnelToDevice(Forwarder.java:119)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.Forwarder.access$300(Forwarder.java:34)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.Forwarder$2.run(Forwarder.java:73)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.RelayTunnel.receive(RelayTunnel.java:101)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.PersistentRelayTunnel.receive(PersistentRelayTunnel.java:64)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.Forwarder.forwardTunnelToDevice(Forwarder.java:119)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.Forwarder.access$300(Forwarder.java:34)
E/PersistentRelayTunnel( 5805):         at com.genymobile.gnirehtet.Forwarder$2.run(Forwarder.java:73)
V/NotificationService(  895): enqueueNotificationInternal: pkg=com.genymobile.gnirehtet id=0 notification=Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 actions=1 vis=PRIVATE)
V/NotificationService(  895): pkg=com.genymobile.gnirehtet canInterrupt=true intercept=false
D/PhoneStatusBar( 1351): addNotification key=0|com.genymobile.gnirehtet|0|null|10139
V/NotificationService(  895): enqueueNotificationInternal: pkg=com.genymobile.gnirehtet id=0 notification=Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 actions=1 vis=PRIVATE)
V/NotificationService(  895): pkg=com.genymobile.gnirehtet canInterrupt=true intercept=false
```

**Comment by rom1v** [comment]
Is the relay server correctly started?

From the computer, execute this command to see if it connects:

    nc localhost 31416

What if you start it [manually](https://github.com/Genymobile/gnirehtet/blob/master/README.md#run-manually):

    java -jar relay.jar

Did you enable port forwarding?

    adb reverse tcp:31416 tcp:31416

**Comment by godofrayer** [comment]
I am using windows. I can check that the relay server is started correctly 
```
F:\gnirehtet-v1.1.1>netstat -na | find "31416"
  TCP    127.0.0.1:31416        0.0.0.0:0              LISTENING
```
And shows command promp with its status as you run `java -jar relay.jar`

I can execute command `adb reverse tcp:31416 tcp:31416` but nothing happens in my command prompt. I think the trouble is with my android. How can i check if port 31416 is not blocked in my android?

**Comment by godofrayer** [comment]
Oh, btw i can check it my android port. Is it correct status?
```
127|root@Grand2:/ # netstat
Proto Recv-Q Send-Q Local Address          Foreign Address        State
 tcp       0      0 127.0.0.1:31416        0.0.0.0:*              LISTEN
tcp6       0      0 ::ffff:127.0.0.1:43322 :::*                   LISTEN
tcp6       0      0 ::ffff:192.168.100.3:46408 ::ffff:103.7.30.157:80 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:52038 ::ffff:74.125.68.188:5228 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:38967 ::ffff:203.205.143.147:80 ESTABLISHED
tcp6       0     10 ::ffff:192.168.100.3:40536 ::ffff:203.205.143.147:14000 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:36412 ::ffff:103.7.30.157:80 ESTABLISHED
tcp6       1      0 ::ffff:192.168.100.3:34675 ::ffff:103.235.46.18:80 CLOSE_WAIT
tcp6       0     10 ::ffff:192.168.100.3:44123 ::ffff:203.205.143.147:14000 ESTABLISHED
tcp6       0     10 ::ffff:192.168.100.3:58422 ::ffff:203.205.143.147:14000 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:41597 ::ffff:14.17.43.118:80 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:49515 ::ffff:172.217.24.74:443 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:55070 ::ffff:216.58.221.46:80 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:34020 ::ffff:203.205.143.147:80 ESTABLISHED
tcp6       0      0 ::ffff:192.168.100.3:47572 ::ffff:203.205.143.147:80 ESTABLISHED
udp6       0      0 :::546                 :::*                   CLOSE
```

**Comment by rom1v** [comment]
```
F:\gnirehtet-v1.1.1>netstat -na | find "31416"
  TCP    127.0.0.1:31416        0.0.0.0:0              LISTENING
```
So it seems that the relay server is correctly listening.

```
root@Grand2:/ # netstat
…
 tcp       0      0 127.0.0.1:31416        0.0.0.0:*              LISTEN
```
So it seems that the reverse port forwarding is enabled…

Then, I don't know what's the problem.

Try to open a simple TCP socket from the Android device to localhost:31416, it should print a log in the relay server window… Unfortunately, there is no command-line tool available in Android by default to do this…

**Comment by ManoLingam96** [comment]
Hello there. 
I too have the same issue. I have verified that the port is open in my pc. I used [`this app`](https://play.google.com/store/apps/details?id=com.eolwral.osmonitor.legacy) to look if the port is open and I couldn't find it (refer attached screenshot).
![screenshot_20170613-113028](https://user-images.githubusercontent.com/15856498/27068177-54891a20-502c-11e7-92f0-259e038438bf.png)
So, what is wrong and how do I fix it?

**Comment by rom1v** [comment]
Could you check that reverse forwarding is actually enabled:

    adb reverse --list

It should print something like:

    (null) tcp:31416 tcp:31416

What is the result of:

    adb shell 'netstat | grep 31416'

?

@ManoLingam96 on Windows?

**Comment by ManoLingam96** [comment]
Actually, its working for me now. I wasn't able to run `adb reverse`. So I decided to update/reinstall adb. I suuggest @godofrayer to try the same. Thanks to @rom1v anyways!

**Comment by rom1v** [comment]
@godofrayer Does it solve the issue for you?
