### ISSUE TITLE
command adb , returned value 1

### ISSUE THREAD

**Issue by anoopyadav7929** [Genymobile/gnirehtet#321]
:\Users\anoop\Desktop\gnirehtet>gnirehtet run
2020-08-22 12:38:16.232 INFO Main: Checking gnirehtet client...
2020-08-22 12:38:16.232 INFO Main: Starting relay server on port 31416...
2020-08-22 12:38:16.237 INFO Relay: Relay server started
2020-08-22 12:38:16.278 ERROR Main: Cannot start client: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value 1

**Comment by NightmareTwily** [comment]
Device isn't adb authorized. Follow this to authorize it https://stackoverflow.com/questions/23081263/adb-android-device-unauthorized

**Comment by anoopyadav7929** [comment]
the device was read already , now i got this problem when i tried everything 


C:\Users\anoop\Desktop\gnirehtet>gnirehtet run
2020-08-26 19:24:55.471 INFO Main: Checking gnirehtet client...
2020-08-26 19:24:55.471 INFO Main: Starting relay server on port 31416...
2020-08-26 19:24:55.587 INFO Relay: Relay server started
2020-08-26 19:24:55.702 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=21415, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=21415, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1134)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:953)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:628)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1732)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:559)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1152)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1123)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3980)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:544)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:175)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10798)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4814)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3067)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:99)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-08-26 19:24:55.875 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by anoopyadav7929** [comment]
can anyone help me out with this one

**Comment by anoopyadav7929** [comment]
@rom1v  i m really new to this stuff, i was just finding way to do reverse debbuging , i dont know , how and where , and method to write this all command that are told in comments, in these articles they say try this , change this with this , i dont know where and how to do it , can u help me with it

**Comment by Biswa96** [comment]
This is UNOFFICIAL. I have created an APK for MIUI specific devices. Download the APK file from here https://github.com/Biswa96/gnirehtet-miui/releases. Rename it to `gnirehtet.apk` and the rest is same as this repository.

**Comment by anoopyadav7929** [comment]
@Biswa96  thnks for help , but i can't understand how to write this all can anyone helpme to execute and tell how to and where i have to write and edit these files

**Comment by anoopyadav7929** [comment]
when i use this , this comes , not happening like #5  
adb pull //system/priv-app/Shell/Shell.apk
//system/priv-app/Shell/Shell.apk: 1 file pulled, 0 skipped. 7.5 MB/s (352433 bytes in 0.045s)
