### ISSUE TITLE
error in realme devices 

### ISSUE THREAD

**Issue by ritenegi** [Genymobile/gnirehtet#322]
2020-08-23 23:24:54.722 INFO Main: Starting relay server on port 31416...
2020-08-23 23:24:54.722 INFO Main: Checking gnirehtet client...
2020-08-23 23:24:54.723 INFO Relay: Relay server started
2020-08-23 23:24:54.846 INFO Main: Installing gnirehtet client...
Performing Streamed Install
Success
2020-08-23 23:24:56.232 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=10410, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=10410, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1151)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:968)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:633)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1730)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:564)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1154)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1118)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3933)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:518)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10789)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4814)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3029)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:99)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-08-23 23:24:56.421 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
#5
