### ISSUE TITLE
Realme 6 PRO USB Debugging Enabled but can't use gnirehtet

### ISSUE THREAD

**Issue by MarioWRLD** [Genymobile/gnirehtet#324]
2020-08-25 14:51:31.802 INFO Main: Starting relay server on port 31416...
2020-08-25 14:51:31.805 INFO Relay: Relay server started
2020-08-25 14:51:31.802 INFO Main: Checking gnirehtet client...
2020-08-25 14:51:32.276 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=11281, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=11281, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1163)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:989)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:641)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1813)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:572)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1157)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1121)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3916)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:518)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10813)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4814)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3021)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:99)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-08-25 14:51:32.576 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
#5
