### ISSUE TITLE
internet not connecting 

### ISSUE THREAD

**Issue by vinay7527852** [Genymobile/gnirehtet#325]
i do everything 
internet not connecting

showing this... probem please help

Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=16470, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=16470, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1922)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:1202)
        at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:659)
        at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:2233)
        at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:597)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5996)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5970)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
        at android.os.ShellCommand.exec(ShellCommand.java:103)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:18770)
        at android.os.Binder.shellCommand(Binder.java:634)
        at android.os.Binder.onTransact(Binder.java:532)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3513)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3800)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:793)
        at android.os.Binder.execTransact(Binder.java:731)
2020-08-31 22:28:06.262 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
#5
