### ISSUE TITLE
not supporting latest os on android 

### ISSUE THREAD

**Issue by ahmadabdelsattar** [Genymobile/gnirehtet#335]
my friend has a oppo reno 2  f and the latest os for android and every time we try to setup  gnirehtet the application mention it is un able to setup the app on the phone as it is restricted from installing on the phone 
i tried to let the phone allow installation from every supported resource 
but no luck in making gnirehtet setup its component on the phone 
kindly help me 
the same problem is in samsung galaxy s10

**Comment by rom1v** [comment]
What is the exact error message?

**Comment by ahmadabdelsattar** [comment]
![Untitled](https://user-images.githubusercontent.com/49734392/96723599-97899b80-1363-11eb-9f80-6198e2a485d6.png)

**Comment by ahmadabdelsattar** [comment]
here is the error i get

**Comment by rom1v** [comment]
(in the future, please copy-paste text instead of screenshot)

See #5.

**Comment by ahmadabdelsattar** [comment]
2020-10-21 15:38:07.608 INFO Main: Checking gnirehtet client...
2020-10-21 15:38:07.608 INFO Main: Starting relay server on port 31416...
2020-10-21 15:38:07.608 INFO Relay: Relay server started
2020-10-21 15:38:07.677 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=11308, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=11308, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1136)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:949)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:626)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1740)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:557)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1170)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1141)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4007)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:544)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:175)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10876)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4850)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3094)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:99)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-10-21 15:38:07.793 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by ahmadabdelsattar** [comment]
i didn't understand the solution 
could you give me the straight answer here so i can apply it 
because i got lost between the details
