### ISSUE TITLE
android.os.NetworkOnMainThreadException when using DNS

### ISSUE THREAD

**Issue by untungs** [Genymobile/gnirehtet#339]
Hi, I'm experiencing an issue when starting gnirehtet java (v2.5).
I'm using Android Q API 29 (Real device & Emulator).

Here's the log when I run **./gnirehtet run -d {ip_address}**. It just stuck at the Starting...

```
2020-11-11 12:39:47.616 I Gnirehtet: Checking gnirehtet client...
2020-11-11 12:39:47.616 I Gnirehtet: Starting relay server on port 31416...
2020-11-11 12:39:47.648 I Relay: Relay server started
2020-11-11 12:39:47.654 I Gnirehtet: Installing gnirehtet client...
Performing Streamed Install
Success
2020-11-11 12:39:48.577 I Gnirehtet: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity (has extras) }
```

And here's the adb logcat

```
2020-11-11 12:39:48.018 5816-5816/com.genymobile.gnirehtet D/GnirehtetActivity: Received request com.genymobile.gnirehtet.START
2020-11-11 12:39:48.025 5816-5816/com.genymobile.gnirehtet D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-11-11 12:39:48.026 5816-5816/com.genymobile.gnirehtet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.genymobile.gnirehtet, PID: 5816
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.genymobile.gnirehtet/com.genymobile.gnirehtet.GnirehtetActivity}: android.os.NetworkOnMainThreadException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
        at java.net.InetAddress.getByName(InetAddress.java:1106)
        at com.genymobile.gnirehtet.Net.toInetAddress(Net.java:38)
        at com.genymobile.gnirehtet.Net.toInetAddresses(Net.java:31)
        at com.genymobile.gnirehtet.GnirehtetActivity.createConfig(GnirehtetActivity.java:62)
        at com.genymobile.gnirehtet.GnirehtetActivity.handleIntent(GnirehtetActivity.java:42)
        at com.genymobile.gnirehtet.GnirehtetActivity.onCreate(GnirehtetActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-11-11 12:39:48.029 30113-31246/system_process W/ActivityTaskManager:   Force finishing activity com.genymobile.gnirehtet/.GnirehtetActivity
```

Thanks

**Comment by rom1v** [comment]
For information, what value do you pass as ip address? Is it a valid IP address?

I can reproduce the issue only if I pass an invalid IP address (for example `8.8.8.400`).

**Comment by untungs** [comment]
You're right, I had the wrong IP address: x.x.259.x which should've been x.x.250.x 😅

I'm closing this issue. Thanks.
