### ISSUE TITLE
Sorry dont know how to explain my error im not that techy

### ISSUE THREAD

**Issue by Rabeenous** [Genymobile/gnirehtet#353]
2021-01-10 11:17:45.366 INFO Main: Starting relay server on port 31416...
2021-01-10 11:17:45.366 INFO Main: Checking gnirehtet client...
2021-01-10 11:17:45.368 INFO Relay: Relay server started
2021-01-10 11:17:45.525 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=20633, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=20633, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1224)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:948)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:632)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1749)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:563)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1188)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1152)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3951)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:518)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10772)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4788)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3050)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:127)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-01-10 11:17:45.742 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by toolonely** [comment]
looks similar to https://github.com/Genymobile/gnirehtet/issues/5
