### ISSUE TITLE
Relay doesn't start

### ISSUE THREAD

**Issue by Aito10** [Genymobile/gnirehtet#358]
PS C:\Users\Shop\Downloads\Compressed\gnirehtet-java 1> .\gnirehtet autorun
2021-02-04 21:02:34.152 I Gnirehtet: Starting relay server on port 31416...
2021-02-04 21:02:34.222 I Relay: Relay server started
2021-02-04 21:02:34.232 I Gnirehtet: Checking gnirehtet client...
2021-02-04 21:02:34.482 E AdbMonitor: Failed to monitor adb devices
java.io.IOException: An existing connection was forcibly closed by the remote ho
st
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(Unknown Source)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
        at sun.nio.ch.IOUtil.read(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
        at com.genymobile.gnirehtet.AdbMonitor.fillBufferFrom(AdbMonitor.java:12
8)
        at com.genymobile.gnirehtet.AdbMonitor.nextPacket(AdbMonitor.java:120)
        at com.genymobile.gnirehtet.AdbMonitor.trackDevicesOnChannel(AdbMonitor.
java:90)
        at com.genymobile.gnirehtet.AdbMonitor.trackDevices(AdbMonitor.java:76)
        at com.genymobile.gnirehtet.AdbMonitor.monitor(AdbMonitor.java:64)
        at com.genymobile.gnirehtet.Main.cmdAutostart(Main.java:290)
        at com.genymobile.gnirehtet.Main.lambda$cmdAutorun$1(Main.java:253)
        at java.lang.Thread.run(Unknown Source)
2021-02-04 21:02:34.502 I AdbMonitor: Restarting adb deamon

**Comment by rom1v** [comment]
You probably have another version of adb running somewhere. If you execute `adb devices` from the gnirehtet directory, does it works immediately?

**Comment by Aito10** [comment]
Thanks for the reply... But how do i execute adb devices..?

**Comment by gingercookies** [comment]
> Thanks for the reply... But how do i execute adb devices..?

Find where you extract Android SDK platform tools, hold shift + right click  and choose "Open PowerShell windows here"
After that you can excute adb devices by command  ./adb devices 
![image](https://user-images.githubusercontent.com/77981365/107458961-b9639400-6b87-11eb-9688-1eb775ec5ae2.png)

**Comment by rom1v** [comment]
> adb server version (36) doesn't match this client (41); killing...

You have several adb daemon running. Find the other (old) adb running on your computer, and use the same for both gnirehtet and your other adb-dependant programs.
