### ISSUE TITLE
Unable to work on android 10 

### ISSUE THREAD

**Issue by enshaw** [Genymobile/gnirehtet#360]
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=16753, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=16753, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1155)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:979)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:636)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1803)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:567)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1157)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1121)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3882)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:518)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10728)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4789)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2998)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:99)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-02-16 16:15:00.637 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
#5

**Comment by enshaw** [comment]
> #5

Now its working
Thanks
