### ISSUE TITLE
gnirentet.exe run displays an error and wont open up the connection prompt thing on my phone

### ISSUE THREAD

**Issue by Leuqas** [Genymobile/gnirehtet#437]
im on android, specificaly, oppo, i have usb debugging and file transfer enabled, gnirehtet.exe install works fine but when i try to start it, it displays an error, heres the error msg
`>gnirehtet run
2022-04-28 09:52:05.437 INFO Main: Checking gnirehtet client...
2022-04-28 09:52:05.437 INFO Main: Starting relay server on port 31416...
2022-04-28 09:52:05.439 INFO Relay: Relay server started
2022-04-28 09:52:05.604 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=22796, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=22796, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1153)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:959)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:632)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1749)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:563)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1182)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1153)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3977)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:543)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:174)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10855)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4769)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3069)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:126)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2022-04-28 09:52:05.836 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255`

**Comment by Leuqas** [comment]
i fixed it by disabling perms monitoring

**Comment by rom1v** [comment]
#5
