### ISSUE TITLE
Permission denial  on the wearos  smartwatch

### ISSUE THREAD

**Issue by lasyka** [Genymobile/gnirehtet#441]
Can't run on wearos smartwatch
```
ActivityManager: Permission Denial: starting Intent { cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub } from ProcessRecord{16f1c1d 12544:com.genymobile.gnirehtet/u0a57} (pid=12544, uid=10057) not exported from uid 10039
05-05 20:53:33.497 12544 12544 E AndroidRuntime: Process: com.genymobile.gnirehtet, PID: 12544
05-05 20:53:33.497 12544 12544 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.genymobile.gnirehtet/com.genymobile.gnirehtet.GnirehtetActivity}: java.lang.SecurityException: Permission Denial: starting Intent { cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub } from ProcessRecord{16f1c1d 12544:com.genymobile.gnirehtet/u0a57} (pid=12544, uid=10057) not exported from uid 10039
05-05 20:53:33.497 12544 12544 E AndroidRuntime: Caused by: java.lang.SecurityException: Permission Denial: starting Intent { cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub } from ProcessRecord{16f1c1d 12544:com.genymobile.gnirehtet/u0a57} (pid=12544, uid=10057) not exported from uid 10039
05-05 20:53:33.497 12544 12544 E AndroidRuntime: 	at com.genymobile.gnirehtet.GnirehtetActivity.requestAuthorization(GnirehtetActivity.java:85)
05-05 20:53:33.497 12544 12544 E AndroidRuntime: 	at com.genymobile.gnirehtet.GnirehtetActivity.startGnirehtet(GnirehtetActivity.java:75)
05-05 20:53:33.497 12544 12544 E AndroidRuntime: 	at com.genymobile.gnirehtet.GnirehtetActivity.handleIntent(GnirehtetActivity.java:43)
05-05 20:53:33.497 12544 12544 E AndroidRuntime: 	at com.genymobile.gnirehtet.GnirehtetActivity.onCreate(GnirehtetActivity.java:34)
05-05 20:53:33.508  1354  4438 W ActivityManager:   Force finishing activity com.genymobile.gnirehtet/.GnirehtetActivity
05-05 20:53:33.619  1354  1640 I ActivityManager: Process com.genymobile.gnirehtet (pid 12544) has died: cch  CRE 
```

**Comment by kotya341** [comment]
folks, do you have any update how to fix this?
