### ISSUE TITLE
Can't establish connection

### ISSUE THREAD

**Issue by MisterP1999** [Genymobile/gnirehtet#471]
I'm getting this error on my Narzo 50. The gnirehtet app is installed via cmd. The drivers for my phone is installed. What should I do?

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=8565, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1117)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1089)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:731)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1266)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1231)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3177)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:567)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:198)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9350)
        at android.os.Binder.shellCommand(Binder.java:970)
        at android.os.Binder.onTransact(Binder.java:854)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5240)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2702)
        at android.os.Binder.execTransactInternal(Binder.java:1226)
        at android.os.Binder.execTransact(Binder.java:1163)
2022-11-21 11:54:27.121 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value -1

**Comment by rom1v** [comment]
#5

**Comment by Leuchak** [comment]
The proposed solutions do not work with android 12.
"Disable permission monitoring" is not present with android version 12.
The solution for android 11 is also not available anymore. "USB debugging (Security Settings)" doesn't exist anymore either.

I looked at [scrcpy#3293](https://github.com/Genymobile/scrcpy/issues/3293#issuecomment-1239562589) and [#302 (comment)](https://github.com/Genymobile/gnirehtet/issues/302#issuecomment-973850470)
