### ISSUE TITLE
How do I fix this Error in running gnirehtet?

### ISSUE THREAD

**Issue by rezyyyy** [Genymobile/gnirehtet#485]
C:\TEST>gnirehtet run
2023-03-09 19:47:55.204 INFO Main: Starting relay server on port 31416...
2023-03-09 19:47:55.204 INFO Main: Checking gnirehtet client...
2023-03-09 19:47:55.209 INFO Relay: Relay server started
2023-03-09 19:47:55.346 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=3151, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1118)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1074)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:736)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1297)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1267)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:2999)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:572)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:193)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:8899)
        at android.os.Binder.shellCommand(Binder.java:953)
        at android.os.Binder.onTransact(Binder.java:837)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5332)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2559)
        at android.os.Binder.execTransactInternal(Binder.java:1187)
        at android.os.Binder.execTransact(Binder.java:1146)
2023-03-09 19:47:55.580 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
#5

**Comment by rezyyyy** [comment]
when i try to locate shell:

C:\TEST>$ adb shell pm list package -f com.android.shell
'$' is not recognized as an internal or external command,
operable program or batch file.

C:\TEST>package:/system/priv-app/Shell/Shell.apk=com.android.shell
'package:' is not recognized as an internal or external command,
operable program or batch file.

skipping step 1 and executing step 2:

C:\TEST>adb pull /system/priv-app/Shell/Shell.apk
/system/priv-app/Shell/Shell.apk: 1 file pulled, 0 skipped. 19.2 MB/s (408344 bytes in 0.020s)

printing its permissions:

C:\TEST>aapt d permissions Shell.apk
'aapt' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rezyyyy** [comment]
its giving this error:

C:\TEST>aapt d permissions Shell.apk
'aapt' is not recognized as an internal or external command,
operable program or batch file.

**Comment by rezyyyy** [comment]
also:
 C:\TEST>adb shell id
adb shell cat /proc/'$$'/statusuid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),1078(ext_data_rw),1079(ext_obb_rw),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc),3011(uhid),3012 context=u:r:shell:s0

**Comment by Shinora007** [comment]
Turning on `Disable Permission Monitoring` worked for me.

found this fix here.
https://stackoverflow.com/a/57721719

**Comment by rezyyyy** [comment]
disabling permission monitoring is not possible for me since im unable to connect to the internet via my phone. So I needed a workaround to access internet by reverse tethering. Is there any way to bypass the (Disable Permission Monitoring) option and gain access?

**Comment by Linus789** [comment]
@rezyyyy One possibility I can think of is to remove [this line](https://github.com/Genymobile/gnirehtet/blob/848a3caa3ed6f3ada7972db102eccedbfde5807a/app/src/main/AndroidManifest.xml#L20) and build the app yourself.
