### ISSUE TITLE
Cannot receive from tunnel: java.io.EOFException

### ISSUE THREAD

**Issue by AlphaBs** [Genymobile/gnirehtet#488]
No internet connection.

`gnirehtet run` command starts relay server and vpn normally but gnirehtet app seems crash immediately.

relay server log:
```
2023-03-13 09:09:07.154 INFO Main: Checking gnirehtet client...
2023-03-13 09:09:07.154 INFO Main: Starting relay server on port 31416...
2023-03-13 09:09:07.155 INFO Relay: Relay server started
2023-03-13 09:09:07.304 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
```
I think it should print `Client #0 commected` but there are no more log.

logcat: 

it said `Cannot receive from tunnel`, `java.io.EOFException` and `Unexpected packet IP version: 6`

```
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: Cannot receive from tunnel
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: java.io.EOFException
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at java.io.DataInputStream.readFully(DataInputStream.java:205)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at java.io.DataInputStream.readInt(DataInputStream.java:394)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.RelayTunnel.readClientId(RelayTunnel.java:72)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.RelayTunnel.connect(RelayTunnel.java:50)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.RelayTunnelProvider.connectTunnel(RelayTunnelProvider.java:77)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.RelayTunnelProvider.getCurrentTunnel(RelayTunnelProvider.java:70)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.PersistentRelayTunnel.receive(PersistentRelayTunnel.java:63)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.Forwarder.forwardTunnelToDevice(Forwarder.java:126)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.Forwarder.access$300(Forwarder.java:34)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at com.genymobile.gnirehtet.Forwarder$2.run(Forwarder.java:73)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
03-12 17:57:54.033 25927 25953 E PersistentRelayTunnel: 	at java.lang.Thread.run(Thread.java:1012)
03-12 17:57:54.033 25927 25953 D PersistentRelayTunnel: Tunnel read EOF
03-12 17:57:54.033 25927 25927 D GnirehtetService: Relay tunnel disconnected
03-12 17:57:54.034 25927 26027 W Forwarder: Unexpected packet IP version: 6
03-12 17:57:54.034 25927 26027 W Forwarder: Unexpected packet IP version: 6
03-12 17:57:54.034 25927 26027 W Forwarder: Unexpected packet IP version: 6
```
tested on Galaxy Tab S8+ (Android 13)
I tried both relay server implementation, same result.

maybe related to #69 #273?

**Comment by AlphaBs** [comment]
[logcat.txt](https://github.com/Genymobile/gnirehtet/files/10955725/logcat.txt)

**Comment by AlphaBs** [comment]
it was `adb reverse` problem. not much related to this.
