### ISSUE TITLE
Does not work with MIUI 14

### ISSUE THREAD

**Issue by cymansplayground** [Genymobile/gnirehtet#501]
When I tried to use Gnirehtet on my new Android Xiaomi Redmi 12 with MIUI 14, as soon after I granted access for debugging mode after plugin in the USB C cable from my PC to my phone, there was an error visible for about 1 second which I never saw again afterwards. And in the console on my pc I can see the following error:

`2023-07-21 14:53:28.484 INFO Main: Checking gnirehtet client...
2023-07-21 14:53:28.640 INFO Main: Installing gnirehtet client...
Performing Streamed Install
adb: failed to install gnirehtet.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
2023-07-21 14:53:30.134 ERROR Main: Cannot start client: Command adb ["-s", "2d3702f97d74", "install", "-r", "gnirehtet.apk"] returned with value 1`

Can anyone help me with this error?

**Comment by cymansplayground** [comment]
I had to enable `Install via USB` so the installation started. But I already got another error:

> Performing Streamed Install
> Success
> 2023-07-21 15:49:13.854 INFO Main: Starting client...
> Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
> 
> Exception occurred while executing 'start':
> java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=21323, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
>         at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1168)
>         at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1127)
>         at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:783)
>         at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1382)
>         at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1345)
>         at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3256)        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:661)
>         at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:212)
>         at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
>         at android.os.ShellCommand.exec(ShellCommand.java:38)
>         at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9591)
>         at android.os.Binder.shellCommand(Binder.java:1054)
>         at android.os.Binder.onTransact(Binder.java:882)
>         at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5399)
>         at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2726)
>         at android.os.Binder.execTransactInternal(Binder.java:1290)
>         at android.os.Binder.execTransact(Binder.java:1249)
> 2023-07-21 15:49:14.066 ERROR Main: Cannot start client: Command adb ["-s", "2d3702f97d74", "shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255
>

**Comment by cymansplayground** [comment]
I also had to enable `USB Debugging Security Settings`, now I have at least the `VPN` icon appear, but no internet yet...

**Comment by cymansplayground** [comment]
Updated to the latest adb version on my PC, now it finally works! 😀
