### ISSUE TITLE
Trying to make it work in my job's office...

### ISSUE THREAD

**Issue by MarrcosabTTS** [Genymobile/gnirehtet#512]
Hi,

I just followed every step in this tutorial for my Xiaomi 9t pro: https://youtu.be/96J-pHZ1kR0 and i can't make it work. I feel like maybe the problem is Xiaomi , i've always had issues installing a lot of things hehe.

Here are the messages i get when i start the .exe:

```
2023-10-18 10:31:21.120 INFO Main: Starting relay server on port 31416...
2023-10-18 10:31:21.120 INFO Main: Checking gnirehtet client...
2023-10-18 10:31:21.126 INFO Relay: Relay server started
2023-10-18 10:31:21.292 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=16044, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1119)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1099)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:745)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1169)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1141)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3781)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:554)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:186)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10935)
        at android.os.Binder.shellCommand(Binder.java:932)
        at android.os.Binder.onTransact(Binder.java:816)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5258)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2981)
        at android.os.Binder.execTransactInternal(Binder.java:1162)
        at android.os.Binder.execTransact(Binder.java:1126)
2023-10-18 10:31:21.585 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255
```

**Comment by rom1v** [comment]
> requires android.permission.WRITE_SECURE_SETTINGS

#5
