### ISSUE TITLE
someone help me fix this issue please where it says error cannot start client 

### ISSUE THREAD

**Issue by itsaddyby** [Genymobile/gnirehtet#518]
Microsoft Windows [Version 10.0.22631.2715]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Advait Moras\Desktop\gnirehtet-rust-win64>gnirehtet.exe run
2023-11-23 16:25:56.940 INFO Main: Checking gnirehtet client...
2023-11-23 16:25:56.940 INFO Main: Starting relay server on port 31416...
2023-11-23 16:25:56.942 INFO Relay: Relay server started
2023-11-23 16:25:57.030 ERROR Main: Cannot start client: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value 1

**Comment by rom1v** [comment]
Install adb https://github.com/Genymobile/gnirehtet#adb

**Comment by itsaddyby** [comment]
> Install adb https://github.com/Genymobile/gnirehtet#adb

but i have installed already and latest version of it i downloaded gnirehtet yesturday and it was working fine until today

**Comment by rom1v** [comment]
Execute manually:
```
adb shell dumpsys package com.genymobile.gnirehtet
```

What is the result?

**Comment by Safii01** [comment]
> Execute manually:
> 
> ```
> adb shell dumpsys package com.genymobile.gnirehtet
> ```
> 
> What is the result?

Got the same issue and my result is:
Activity Resolver Table:
  Non-Data Actions:
      com.genymobile.gnirehtet.STOP:
        226544a com.genymobile.gnirehtet/.GnirehtetActivity filter 33c9fbb
          Action: "com.genymobile.gnirehtet.START"
          Action: "com.genymobile.gnirehtet.STOP"
      com.genymobile.gnirehtet.START:
        226544a com.genymobile.gnirehtet/.GnirehtetActivity filter 33c9fbb
          Action: "com.genymobile.gnirehtet.START"
          Action: "com.genymobile.gnirehtet.STOP"

Service Resolver Table:
  Non-Data Actions:
      android.net.VpnService:
        f1d2cd8 com.genymobile.gnirehtet/.GnirehtetService filter a261831 permission android.permission.BIND_VPN_SERVICE
          Action: "android.net.VpnService"

Key Set Manager:
  [com.genymobile.gnirehtet]
      Signing KeySets: 65

Packages:
  Package [com.genymobile.gnirehtet] (abece6e):
    userId=10259
    pkg=Package{d37990f com.genymobile.gnirehtet}
    codePath=/data/app/~~CfLESKGDw3mQRpcZDNfiog==/com.genymobile.gnirehtet-7Gfd3dcapoM1ZlDQyaromg==
    resourcePath=/data/app/~~CfLESKGDw3mQRpcZDNfiog==/com.genymobile.gnirehtet-7Gfd3dcapoM1ZlDQyaromg==
    legacyNativeLibraryDir=/data/app/~~CfLESKGDw3mQRpcZDNfiog==/com.genymobile.gnirehtet-7Gfd3dcapoM1ZlDQyaromg==/lib
    primaryCpuAbi=null
    secondaryCpuAbi=null
    versionCode=9 minSdk=21 targetSdk=29
    versionName=2.5.1
    splits=[base]
    apkSigningVersion=2
    applicationInfo=ApplicationInfo{d37990f com.genymobile.gnirehtet}
    flags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]
    privateFlags=[ PRIVATE_FLAG_ACTIVITIES_RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION ALLOW_AUDIO_PLAYBACK_CAPTURE PRIVATE_FLAG_ALLOW_NATIVE_HEAP_POINTER_TAGGING ]
    forceQueryable=false
    queriesPackages=[]
    dataDir=/data/user/0/com.genymobile.gnirehtet
    supportsScreens=[small, medium, large, xlarge, resizeable, anyDensity]
    usesLibraries:
      android.test.base
    usesLibraryFiles:
      /system/framework/android.test.base.jar
    timeStamp=2023-12-14 23:46:31
    firstInstallTime=2023-12-14 23:46:07
    lastUpdateTime=2023-12-14 23:46:34
    installerPackageName=com.coloros.filemanager
    signatures=PackageSignatures{1e8ed9c version:2, signatures:[34346c2c], past signatures:[]}
    installPermissionsFixed=true
    pkgFlags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]
    requested permissions:
      android.permission.ACCESS_NETWORK_STATE
      android.permission.FOREGROUND_SERVICE
      android.permission.INTERNET
    install permissions:
      android.permission.FOREGROUND_SERVICE: granted=true
      android.permission.INTERNET: granted=true
      android.permission.ACCESS_NETWORK_STATE: granted=true
    User 0: ceDataInode=26429 installed=true hidden=false suspended=false distractionFlags=0 stopped=true notLaunched=true enabled=0 ofs=0 instant=false virtual=false
    overlay paths:
      /my_heytap/overlay/GmsConfigOverlayCommon/GmsConfigOverlayCommon.apk
      /my_heytap/overlay/GmsConfigOverlayComms/GmsConfigOverlayComms.apk
      /my_heytap/overlay/GmsConfigOverlayGSA/GmsConfigOverlayGSA.apk
      /product/overlay/GoogleExtServicesConfigOverlay.apk
      /product/overlay/GooglePermissionControllerFrameworkOverlay.apk
      /product/overlay/ModuleMetadataGoogleOverlay.apk
      /product/overlay/FrameworksResCommon.apk
      /product/overlay/FrameworksResCommonQva.apk
      /vendor/overlay/FrameworksResTarget.apk
      /my_product/overlay/android_framework_res_overlay.display.product.20673.apk
      /my_product/overlay/framework_res_overlay_ZERO_TOUCH.20673.apk
      lastDisabledCaller: com.coloros.filemanager
      gids=[3003]
      runtime permissions:

Queries:
  system apps queryable: false
  queries via package name:
    com.genymobile.gnirehtet:
      com.coloros.filemanager
  queries via intent:
  queryable via interaction:
    User 0:

Package Changes:
  Sequence number=551
  User 0:
    seq=7, package=com.facebook.appmanager
    seq=8, package=com.google.android.partnersetup
    seq=9, package=com.google.android.videos
    seq=10, package=com.google.android.apps.maps
    seq=14, package=com.google.android.apps.googleassistant
    seq=15, package=com.google.android.apps.walletnfcrel
    seq=45, package=com.android.chrome
    seq=48, package=com.spotify.lite
    seq=54, package=com.oppo.launcher
    seq=94, package=com.google.android.gsf
    seq=104, package=com.google.android.youtube
    seq=122, package=com.google.android.syncadapters.contacts
    seq=150, package=com.google.android.apps.magazines
    seq=153, package=com.google.android.gms
    seq=154, package=com.android.vending
    seq=386, package=com.spotify.music
    seq=391, package=com.coloros.activation
    seq=392, package=com.google.android.apps.restore
    seq=393, package=com.google.android.googlequicksearchbox
    seq=398, package=com.google.android.apps.wellbeing
    seq=407, package=com.google.android.contacts
    seq=409, package=com.microsoft.launcher
    seq=411, package=com.google.android.apps.youtube.music
    seq=412, package=net.zedge.android
    seq=520, package=com.google.android.setupwizard
    seq=521, package=com.microsoft.bing
    seq=522, package=com.transsion.XOSLauncher
    seq=528, package=com.android.stk
    seq=530, package=com.coloros.sauhelper
    seq=531, package=com.reddit.frontpage
    seq=532, package=com.jazz.jazzworld
    seq=533, package=com.android.shell
    seq=534, package=com.android.settings
    seq=539, package=com.coloros.filemanager
    seq=540, package=com.genymobile.gnirehtet
    seq=541, package=com.whatsapp
    seq=550, package=com.google.android.apps.docs


Dexopt state:
  [com.genymobile.gnirehtet]
    path: /data/app/~~CfLESKGDw3mQRpcZDNfiog==/com.genymobile.gnirehtet-7Gfd3dcapoM1ZlDQyaromg==/base.apk
      arm64: [status=speed-profile] [reason=install]


Compiler stats:
  [com.genymobile.gnirehtet]
     base.apk - 112

APEX session state:
  Session ID: 560107426
    State: STAGED

**Comment by Krzeszny** [comment]
> Execute manually:
> 
> ```
> adb shell dumpsys package com.genymobile.gnirehtet
> ```
> 
> What is the result?

In my case it gives `adb.exe: more than one device/emulator`

**Comment by rom1v** [comment]
The message is quite clear. What is the result of `adb devices`?

**Comment by Krzeszny** [comment]
> The message is quite clear. What is the result of `adb devices`?

2 devices, of course. An offline emulator and Pico 4's ID. I've found someone saying that if there are multiple devices attached, one should use adb -s (ID here) but then I get this:

```
PS C:\Users\krzes\Downloads\gnirehtet-rust-win64-v2.5.1\gnirehtet-rust-win64> adb -s PA8150MGGC061773G dumpsys package com.genymobile-gnirehtet
adb.exe: unknown command dumpsys
```

**Comment by rom1v** [comment]
```
adb -s PA8150MGGC061773G shell dumpsys package com.genymobile.gnirehtet
```

**Comment by Krzeszny** [comment]
Nice. I'm just a bad non-programmer.

```
PS C:\Users\krzes\Downloads\gnirehtet-rust-win64-v2.5.1\gnirehtet-rust-win64> adb -s PA8150MGGC061773G shell dumpsys package com.genymobile.gnirehtet
Activity Resolver Table:
  Non-Data Actions:
      com.genymobile.gnirehtet.STOP:
        74602e4 com.genymobile.gnirehtet/.GnirehtetActivity filter a6b9682
          Action: "com.genymobile.gnirehtet.START"
          Action: "com.genymobile.gnirehtet.STOP"
      com.genymobile.gnirehtet.START:
        74602e4 com.genymobile.gnirehtet/.GnirehtetActivity filter a6b9682
          Action: "com.genymobile.gnirehtet.START"
          Action: "com.genymobile.gnirehtet.STOP"

Service Resolver Table:
  Non-Data Actions:
      android.net.VpnService:
        e08e34d com.genymobile.gnirehtet/.GnirehtetService filter 236e193 permission android.permission.BIND_VPN_SERVICE
          Action: "android.net.VpnService"

Key Set Manager:
  [com.genymobile.gnirehtet]
      Signing KeySets: 16

Packages:
  Package [com.genymobile.gnirehtet] (9986e02):
    userId=10117
    pkg=Package{ef7a313 com.genymobile.gnirehtet}
    codePath=/data/app/com.genymobile.gnirehtet-H-DMg3u8CzmOiIoT4kk6iw==
    resourcePath=/data/app/com.genymobile.gnirehtet-H-DMg3u8CzmOiIoT4kk6iw==
    legacyNativeLibraryDir=/data/app/com.genymobile.gnirehtet-H-DMg3u8CzmOiIoT4kk6iw==/lib
    primaryCpuAbi=null
    secondaryCpuAbi=null
    versionCode=9 minSdk=21 targetSdk=29
    versionName=2.5.1
    splits=[base]
    apkSigningVersion=2
    applicationInfo=ApplicationInfo{6d26950 com.genymobile.gnirehtet}
    flags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]
    privateFlags=[ PRIVATE_FLAG_ACTIVITIES_RESIZE_MODE_RESIZEABLE_VIA_SDK_VERSION ALLOW_AUDIO_PLAYBACK_CAPTURE ]
    dataDir=/data/user/0/com.genymobile.gnirehtet
    supportsScreens=[small, medium, large, xlarge, resizeable, anyDensity]
    timeStamp=2024-03-06 16:10:37
    firstInstallTime=2024-03-06 15:56:16
    lastUpdateTime=2024-03-06 16:10:37
    installerPackageName=com.android.packageinstaller
    signatures=PackageSignatures{78d6749 version:2, signatures:[34346c2c], past signatures:[]}
    installPermissionsFixed=true
    pkgFlags=[ HAS_CODE ALLOW_CLEAR_USER_DATA ]
    requested permissions:
      android.permission.ACCESS_NETWORK_STATE
      android.permission.FOREGROUND_SERVICE
      android.permission.INTERNET
    install permissions:
      android.permission.FOREGROUND_SERVICE: granted=true
      android.permission.INTERNET: granted=true
      android.permission.ACCESS_NETWORK_STATE: granted=true
    User 0: ceDataInode=33274 installed=true hidden=false suspended=false stopped=true notLaunched=true enabled=0 instant=false virtual=false
      lastDisabledCaller: com.android.packageinstaller
      gids=[3003]
      runtime permissions:
    isVrApp: false
    isAllComponentVr: false
    VD density: 200
    VD portrait width: 506
    VD portrait height: 900
    VD landscape width: 1600
    VD landscape height: 900
    VD force orientation: -1
    VD default orientation: 0
    VD launch activity orientation: -1
isSystemUserPackagesBlacklistSupported: false

Package Changes:
  Sequence number=32
  User 0:
    seq=7, package=com.picovr.enterpriseassistant
    seq=8, package=com.pvr.tobhome
    seq=9, package=com.pvr.tobservice
    seq=10, package=com.picovr.tobvrusercenter
    seq=11, package=com.picoxr.tobstore
    seq=12, package=com.bytedance.pico.tob.userservice
    seq=13, package=com.picoxr.bstreamassistant
    seq=20, package=com.aurora.store
    seq=23, package=com.smartoptometry.smartoptometry.full
    seq=27, package=com.picovr.updatesystem
    seq=29, package=com.android.shell
    seq=30, package=com.android.settings
    seq=31, package=com.genymobile.gnirehtet


Dexopt state:
  [com.genymobile.gnirehtet]
    path: /data/app/com.genymobile.gnirehtet-H-DMg3u8CzmOiIoT4kk6iw==/base.apk
      arm64: [status=speed-profile] [reason=install]


Compiler stats:
  [com.genymobile.gnirehtet]
     base.apk - 98

Active APEX packages:


Inactive APEX packages:


Factory APEX packages:


  APEX session state:
```
Ok, now that it does *something*, can you tell me how to make gnirehtet work, please? I'm getting the same error as the OP.

**Comment by Krzeszny** [comment]
@rom1v Could you suggest what I should do next?

**Comment by rom1v** [comment]
Could you paste the whole error you get? Because your adb seems to be working. Did you set an ADB environment variable by any chance?

**Comment by Safii01** [comment]
Idk why I'm getting the email for this issue.

For those who want to know:
My problem wasn't resolved, prolly because the server (pc) app couldn't open the client-side app (phone). 

I tried alot of thing but it was prolly some permission issue on my phone as far as i know.

Anyways, at the end after spending hours and a lot of frustration I just went ahead and used another app.

**Comment by rom1v** [comment]
The permission issue was probably #5.

**Comment by Krzeszny** [comment]
Ok, so the Java version works fine, up to 150Mbit bandwidth on a good-quality USB C-C cable. Same stable bitrate as my cheap  WiFi 5 router (Archer A6 and yes, I've disabled WiFi). Sure, USB OTG Ethernet adapters can support 400Mbit bandwidth or more, but at least "Java tethering" works without BSODs, unlike conventional tethering. Tested for an hour with Virtual Desktop.

It's only the Rust version that won't work, as even if it connects (not sure why it wouldn't connect before but I've made sure to have the device unlocked when I'm starting gnirehtet), the Rust version keeps disconnecting every second, but that's a different issue.

**Comment by rom1v** [comment]
Weird. Which version is it (which number) for Rust and for Java?

**Comment by Krzeszny** [comment]
v2.5.1 for both. I'll open a new issue and tag you if you wanna check out the errors and whatnot.

**Comment by Krzeszny** [comment]
Actually, even the Java version doesn't always work. Sometimes it won't start, only showing this:
```
2024-03-07 18:56:20.674 I Gnirehtet: Checking gnirehtet client...
2024-03-07 18:56:20.674 I Gnirehtet: Starting relay server on port 31416...
2024-03-07 18:56:20.715 E Gnirehtet: Cannot start client
com.genymobile.gnirehtet.relay.CommandExecutionException: Command [adb, shell, dumpsys, package, com.genymobile.gnirehtet] returned with value 1
        at com.genymobile.gnirehtet.Main.mustInstallClient(Main.java:375)
        at com.genymobile.gnirehtet.Main.cmdStart(Main.java:265)
        at com.genymobile.gnirehtet.Main.lambda$asyncStart$3(Main.java:317)
        at java.base/java.lang.Thread.run(Thread.java:1583)
2024-03-07 18:56:20.751 I Relay: Relay server started
```
**But** if you keep trying, it'll eventually start, like with an old car.

**Comment by rom1v** [comment]
It probably depends on whether the device is correctly detected (check `adb devices`).

**Comment by evilnero** [comment]
Try closing or stopping the adb.exe process in Task Manager — it helped in my case.
Sometimes adb.exe remains running in the background for no apparent reason, possibly from a previous session. After ending it manually, the client started correctly.

I edited gnirehtet-run.cmd file:

gnirehtet.exe run
taskkill /IM gnirehtet.exe /F
taskkill /IM adb.exe /F
pause

And don't hit Y when stopping it with CTRL+C, answer N.
