### ISSUE TITLE
anyone knows how to fix this?

### ISSUE THREAD

**Issue by bdknatividad** [Genymobile/gnirehtet#525]
2024-01-10 12:32:13.275 INFO Main: Starting relay server on port 31416...
2024-01-10 12:32:13.275 INFO Main: Checking gnirehtet client...
2024-01-10 12:32:13.278 INFO Relay: Relay server started
2024-01-10 12:32:13.420 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=17925, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1143)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1269)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:803)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1243)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1205)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:4045)        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:572)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:189)
        at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
        at android.os.ShellCommand.exec(ShellCommand.java:44)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:11410)
        at android.os.Binder.shellCommand(Binder.java:936)
        at android.os.Binder.onTransact(Binder.java:820)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5216)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3180)
        at com.android.server.am.OppoActivityManagerService.onTransact(OppoActivityManagerService.java:169)
        at android.os.Binder.execTransactInternal(Binder.java:1166)
        at android.os.Binder.execTransact(Binder.java:1130)
2024-01-10 12:32:13.520 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
#5
