### ISSUE TITLE
Java exception: Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by Krzeszny** [Genymobile/gnirehtet#530]
gnirehtet v2.5.1
Windows 10 64-bit
Java 8 401

First of all, the main Github page says to install Java 8 JRE but that's version 52.
I'm guessing the newest release was compiled using OpenJDK 11, which would be why it wants version 55, but I'm not a programmer so I have no idea how to install Java 11, while Oracle's latest installer is for Java 8.
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/genymobile/gnirehtet/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Press any key to continue . . .
```

**Comment by krai114** [comment]
Download the x64 Installer on https://www.oracle.com/java/technologies/downloads/#jdk21-windows

The installer will do everything for you and it should work.

**Comment by nmateo** [comment]
Could not resolve dependencies for project org.openjfx:sample:jar:1.0.0: The following artifacts could not be resolved: org.openjfx:javafx-controls:jar:8.0.261 (absent), org.openjfx:javafx-fxml:jar:8.0.261 (absent), org.openjfx:javafx-graphics:jar:8.0.261 (absent): org.openjfx:javafx-controls:jar:8.0.261 was not found

**Comment by huliqan** [comment]
> [krai114](/krai114)

this work!!! Fixed now! many thanks!!!
