### ISSUE TITLE
gnirehtet cannot start the client issue

### ISSUE THREAD

**Issue by srivetriselvan** [Genymobile/gnirehtet#532]
**While iam executing a code it shows that** 
```
C:\Users\Srivetriselvan\3D Objects\usb debugging>gnirehtet.exe run
2024-03-31 11:40:06.058 INFO Main: Starting relay server on port 31416...
2024-03-31 11:40:06.059 INFO Main: Checking gnirehtet client...
2024-03-31 11:40:06.061 INFO Relay: Relay server started
2024-03-31 11:40:06.125 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=28897, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1168)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1127)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:783)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1382)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1345)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3257)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:661)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:212)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9632)
        at android.os.Binder.shellCommand(Binder.java:1054)
        at android.os.Binder.onTransact(Binder.java:882)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5399)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2727)
        at android.os.Binder.execTransactInternal(Binder.java:1290)
        at android.os.Binder.execTransact(Binder.java:1249)
2024-03-31 11:40:06.219 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

```
**`how to solve this error please help me.....`**

**Comment by rom1v** [comment]
#5
