### ISSUE TITLE
Please resolve ERROR Main: Cannot start client: Command adb

### ISSUE THREAD

**Issue by RG11210** [Genymobile/gnirehtet#555]
C:\Users\DELL\Downloads\Share internet>gnirehtet install
2024-09-24 12:21:16.419 INFO Main: Installing gnirehtet client...
Performing Streamed Install
Success

C:\Users\DELL\Downloads\Share internet>gnirehtet run
2024-09-24 12:21:23.009 INFO Main: Starting relay server on port 31416...
2024-09-24 12:21:23.009 INFO Main: Checking gnirehtet client...
2024-09-24 12:21:23.011 INFO Relay: Relay server started
2024-09-24 12:21:23.095 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=14961, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1193)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1126)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:771)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1327)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1283)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3383)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:609)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:214)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:9880)
        at android.os.Binder.shellCommand(Binder.java:1073)
        at android.os.Binder.onTransact(Binder.java:901)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4731)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2836)
        at android.os.Binder.execTransactInternal(Binder.java:1331)
        at android.os.Binder.execTransact(Binder.java:1268)
2024-09-24 12:21:23.222 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by Mitche19962311** [comment]
HOLA

**Comment by RG11210** [comment]
What?

**Comment by le0-VV** [comment]
Did you put the adb executable in the same folder as gnirehtet?

**Comment by footaotv** [comment]
Try `gnirehtet autorun` instead of `gnirehtet run`
