### ISSUE TITLE
Permission Denial requires android.permission.WRITE_SECURE_SETTINGS

### ISSUE THREAD

**Issue by user9931** [Genymobile/gnirehtet#566]
**gnirehtet run**

```
2024-11-22 08:12:40.839 INFO Main: Starting relay server on port 31416...
2024-11-22 08:12:40.839 INFO Main: Checking gnirehtet client...
2024-11-22 08:12:40.842 INFO Relay: Relay server started
2024-11-22 08:12:41.082 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }

Exception occurred while executing 'start':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity mCallingUid=2000 } from null (pid=18494, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1243)
        at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1213)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:830)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1432)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1383)
        at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:3572)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:730)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:239)
        at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
        at android.os.ShellCommand.exec(ShellCommand.java:38)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10557)
        at android.os.Binder.shellCommand(Binder.java:1092)
        at android.os.Binder.onTransact(Binder.java:912)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5267)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3005)
        at android.os.Binder.execTransactInternal(Binder.java:1392)
        at android.os.Binder.execTransact(Binder.java:1299)
2024-11-22 08:12:41.233 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255
```

win11, android 14 (realme)

**Comment by JayC180** [comment]
I solved this issue by Disable Permission Monitoring in developer options

**Comment by fareedfauzi** [comment]
Anyone with Mi phone, in Developer options.. Don't forget to 
- Turn on "Install via USB"
- Turn on "USB debugging (Security settings)"
