### ISSUE TITLE
gnirehtet strat error

### ISSUE THREAD

**Issue by zhangailive** [Genymobile/gnirehtet#68]
When the program has just started, the following error are prompted. May I ask what is the reason for it? Thanks!

C:\work\test>gnirehtet.exe run
2017-12-15 14:53:38.160 INFO Main: Checking gnirehtet client...
2017-12-15 14:53:38.243 ERROR Main: Execution error: Command adb ["shell", "dumpsys", "package", "com.genymobile.gnirehtet"] returned with value 1

**Comment by rom1v** [comment]
You need [adb](https://github.com/Genymobile/gnirehtet/blob/master/README.md#adb).

**Comment by zhangailive** [comment]
`2017-12-15 16:06:50.313 INFO UdpConnection: 10.0.0.2:56586 -> 8.8.8.8:53 Open
thread 'main' panicked at '
C:\Users\Administrator\Desktop\gnirehtet-rust-win64>`

**Comment by zhangailive** [comment]
`2017-12-15 16:13:09.165 WARN TcpConnection: 10.0.0.2:33099 -> 106.75.22.236:443
Ignoring packet 1669431084; expecting 1669431085; flags=4
thread 'main' panicked at 'failed printing to stdout: 存储空间不足，无法处理此命令。 (os error
8)', src\libstd\io\stdio.rs:692:8`

**Comment by zhangailive** [comment]
2017-12-15 16:26:24.614 INFO TcpConnection: 10.0.0.2:41288 -> 118.123.210.32:443 Open
thread 'main' panicked at 'Press any key to continue . . .

**Comment by rom1v** [comment]
According to _Google translate_, 存储空间不足，无法处理此命令。means:

> Insufficient memory to process this command.

It seems you're running out of memory…

**Comment by zhangailive** [comment]
Why is it running all the time in the memory of the mobile phone? Do not automatically run a period of time to release memory
？

**Comment by rom1v** [comment]
> Why is it running all the time in the memory of the mobile phone?

The out-of-memory occurs on the computer side.

Since _gnirehtet_ typically uses only several Kb of memory, I think your memory is consumed by something else. Otherwise, there is a serious memory leak. Please check.

**Comment by zhangailive** [comment]
PC restart the service, the mobile phone clears the cache and data, the program can run normally; but browsing the web pages automatically for dozens of seconds

**Comment by Kristian-1** [comment]
Hello,
On Windows 7 64 bits, I've got in the same directory : adb.exe, AdbWinApi.dll,  AdbWinUsbApi.dll, gnirehtet.exe, gnirehtet.apk. When I launch gnirehtet-run.cmd, and granted permission on device as requested,  I get this error :-1: 2018-01-20 19:17:07.532 ERROR Main: Execution error: Command adb ["shell", "dump sys", "package", "com.genymobile.gnirehtet"] returned with value 1

What is wrong?

**Comment by rom1v** [comment]
@Kristian-1 From this directory, what is the result of the command:

    adb devices

?

**Comment by Kristian-1** [comment]
Here is the result of the command:
C:\adb>adb devices
List of devices attached
adb server version (29) doesn't match this client (39); killing...
* daemon started successfully
42002d4df2267400        unauthorized
C:\adb>
Thks

**Comment by Kristian-1** [comment]
Excuse me, I just forgot to give the requested authorization on the phone!
This done, the message is
> 
C:\adb>adb devices
List of devices attached
adb server version (29) doesn't match this client (39); killing...
* daemon started successfully
42002d4df2267400        device
C:\adb>
>

**Comment by rom1v** [comment]
> adb server version (29) doesn't match this client (39); killing...

Do you always have this line?

**Comment by Kristian-1** [comment]
yes, everytime I try, I get this same message.

**Comment by Kristian-1** [comment]
My deviceis a Samsung Galaxy J3 (2016) rooted, running on Lineage 14.1 (Android 7.1)

**Comment by rom1v** [comment]
> yes, everytime I try, I get this same message.

So you probably have a running software that executes (an old version of) `adb` regularly, which kills the one used by _gnirehtet_. Try to find and close this software.

**Comment by Kristian-1** [comment]
Thanks !
I had indeed a synchronization programme with windowsCE device running an older adb. I closed it, so no other version is running.

Hence this command looks clean:
C:\adb>adb devices
List of devices attached
42002d4df2267400        device

BUT when launching I got this message:
2018-01-21 15:02:18.029 INFO Main: Checking gnirehtet client...
2018-01-21 15:02:18.161 INFO Main: Installing gnirehtet client...
adb: failed to install gnirehtet.apk:
Exception occurred while dumping:
java.lang.IllegalStateException: ?Failed to prepare session dir: /data/app/vmdl4
45803863.tmp
        at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
        at com.android.server.pm.PackageInstallerService.openSession(PackageInst
allerService.java:756)
        at com.android.server.pm.PackageManagerShellCommand.doWriteSplit(Package
ManagerShellCommand.java:1194)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageMa
nagerShellCommand.java:176)
        at com.android.ser2018-01-21 15:02:18.325 ERROR Main: Execution error: C
ommand adb ["install", "-r", "gnirehtet.apk"] returned with value 1
Appuyez sur une touche pour continuer...

**Comment by rom1v** [comment]
What happens if you execute directly:

    adb install gnirehtet.apk

?

**Comment by Kristian-1** [comment]
> What happens if you execute directly:
adb install gnirehtet.apk?
> 
This answer (that I can't decipher :-( ):
C:\adb>adb install gnirehtet.apk
adb: failed to install gnirehtet.apk:
Exception occurred while dumping:
java.lang.IllegalStateException: ?Failed to prepare session dir: /data/app/vmdl8
03633278.tmp
        at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
        at com.android.server.pm.PackageInstallerService.openSession(PackageInst
allerService.java:756)
        at com.android.server.pm.PackageManagerShellCommand.doWriteSplit(Package
ManagerShellCommand.java:1194)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageMa
nagerShellCommand.java:176)
        at com.android.ser
C:\adb>

**Comment by rom1v** [comment]
OK, it seems your device ROM has a problem, which is not related to _gnirehtet_ (you can't install an application using the standard `adb` command).

**Comment by nandayra** [comment]
o meu não conecta só aparece essa mensagem

2020-10-20 00:46:23.247 INFO Main: Checking gnirehtet client...
2020-10-20 00:46:23.247 INFO Main: Starting relay server on port 31416...
2020-10-20 00:46:23.252 INFO Relay: Relay server started
2020-10-20 00:46:23.527 INFO Main: Starting client...
Starting: Intent { act=com.genymobile.gnirehtet.START cmp=com.genymobile.gnirehtet/.GnirehtetActivity }
Security exception: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=10354, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Permission Denial: starting Intent { act=com.genymobile.gnirehtet.START flg=0x10000000 cmp=com.genymobile.gnirehtet/.GnirehtetActivity } from null (pid=10354, uid=2000) requires android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1089)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:788)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:587)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1389)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:518)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1089)
        at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1063)
        at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3560)
        at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:518)
        at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:172)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:10065)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4665)
        at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2790)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-10-20 00:46:23.808 ERROR Main: Cannot start client: Command adb ["shell", "am", "start", "-a", "com.genymobile.gnirehtet.START", "-n", "com.genymobile.gnirehtet/.GnirehtetActivity"] returned with value 255

**Comment by rom1v** [comment]
#5
