### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by RMcD94** [Genymobile/gnirehtet#72]
C:\Users\faithcafe\Desktop\gnirehtet-java>gnirehtet run
2017-12-30 15:27:47.794 I Gnirehtet: Checking gnirehtet client...
Exception in thread "main" com.genymobile.gnirehtet.relay.CommandExecutionExcept
ion: Command [adb, shell, dumpsys, package, com.genymobile.gnirehtet] returned w
ith value 1
        at com.genymobile.gnirehtet.Main.mustInstallApk(Main.java:229)
        at com.genymobile.gnirehtet.Main.access$200(Main.java:32)
        at com.genymobile.gnirehtet.Main$Command$4.execute(Main.java:95)
        at com.genymobile.gnirehtet.Main.main(Main.java:329)

I have been trying for a few days to get this working at some internet cafes but I continually run into issues such as ABD not detecting my device and things like that. But now that I have that working and after installing the latest java I get this error.

**Comment by rom1v** [comment]
It seems `adb` is not in your `PATH`.

See https://github.com/Genymobile/gnirehtet/blob/master/README.md#adb

**Comment by RMcD94** [comment]
I had done that, they were in the same folder. Debugging is enabled.

I gave up on that computer and found one that was 64 bit so I could use the Rust version, but this time I get the problem with adb not detecting my device except it shows up in adb devices so...

https://i.imgur.com/xa99ASy.png

Thanks for the help and for the program. I know that it'll be very useful once I can get it to work.

**Comment by RMcD94** [comment]
Scratch that I'm an idiot and didn't authorize it, it's working now. It's working perfectly, thank you.
