### ISSUE TITLE
Apk install - INSTALL_FAILED_OLDER_SDK

### ISSUE THREAD

**Issue by vb078** [Genymobile/gnirehtet#77]
Hello

I realy love gnirehtet concept ;)
I am on mac, using android 4.4.2
I try to get SDK version from adb :
```
$ adb shell getprop ro.build.version.sdk
19
$ adb shell getprop ro.build.version.release
4.4.2
```
The connexion seems to work, I have a key confirmation on my phone.
But, if I understand well, I need to install the apk (with adb installed with 'brew')
and, when I try I have two errors :
1) INSTALL_FAILED_OLDER_SDK]
2) different versions of 'client' and 'server' (says adb)

```
./gnirehtet run
2018-01-06 03:25:14.763 I Gnirehtet: Checking gnirehtet client...
2018-01-06 03:25:19.256 I Gnirehtet: Installing gnirehtet client...
gnirehtet.apk: 1 file pushed. 0.9 MB/s (20616 bytes in 0.022s)
	pkg: /data/local/tmp/gnirehtet.apk
Failure [INSTALL_FAILED_OLDER_SDK]
2018-01-06 03:25:22.561 I Gnirehtet: Starting client...
2018-01-06 03:25:22.574 I Gnirehtet: Starting relay server...
error: closed
2018-01-06 03:25:22.622 E Gnirehtet: Cannot start client
com.genymobile.gnirehtet.relay.CommandExecutionException: Command [adb, reverse, tcp:31416, tcp:31416] returned with value 1
	at com.genymobile.gnirehtet.Main.execSync(Main.java:218)
	at com.genymobile.gnirehtet.Main.execAdb(Main.java:192)
	at com.genymobile.gnirehtet.Main.startClient(Main.java:246)
	at com.genymobile.gnirehtet.Main.access$500(Main.java:32)
	at com.genymobile.gnirehtet.Main$Command$4.lambda$execute$0(Main.java:104)
	at java.lang.Thread.run(Thread.java:745)
2018-01-06 03:25:23.138 I Relay: Relay server started
```
Can you help ?
I dont know how to change 'minSdkVersion' and 'maxSdkVersion'...
I try 'apktool'... to decompil and change it.

I try [fdmobileinventions reversetethering](http://fdmobileinventions.blogspot.com/p/reversetethering-server.html) (working great but not so open)

Have a good day

**Comment by rom1v** [comment]
It requires Android 5. See https://github.com/Genymobile/gnirehtet/issues/2

**Comment by vb078** [comment]
Ok, thanks, I didnt see it.

**Comment by justmejust** [comment]
why not make it a universal that can be work over any android version?
