### ISSUE TITLE
gnirehtet fails to install

### ISSUE THREAD

**Issue by Eimpau** [Genymobile/gnirehtet#98]
First time on github
This is what I wrote on the git bash

```
$ ./gnirehtet install
2018-03-27 22:36:06.237 I Gnirehtet: Installing gnirehtet client...
Exception in thread "main" java.io.IOException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at com.genymobile.gnirehtet.Main.execSync(Main.java:334)
        at com.genymobile.gnirehtet.Main.execAdb(Main.java:311)
        at com.genymobile.gnirehtet.Main.cmdInstall(Main.java:206)
        at com.genymobile.gnirehtet.Main.access$100(Main.java:32)
        at com.genymobile.gnirehtet.Main$Command$1.execute(Main.java:52)
        at com.genymobile.gnirehtet.Main.main(Main.java:428)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 7 more
```

**Comment by rom1v** [comment]
You need [adb](https://github.com/Genymobile/gnirehtet/blob/master/README.md#adb).
